import { useEffect, useState } from 'react';

/**
 * Shared data layer for Ayush's photo wall.
 *
 * The list of pictures lives in `public/photos/ayush/manifest.json`, generated by
 * `npm run photos` (see scripts/prepare-photos.mjs). Drop more photos in, re-run that
 * command, and the background wall + Photo Mode pick them up automatically.
 */

export interface WallPhoto {
  id: string;
  file: string;
  /** Full-size image, used on the Photo Mode stage. */
  src: string;
  /** Small preview used for the dim background wall, filmstrip and grid. */
  thumb: string;
  title: string;
  caption?: string;
}

const MANIFEST_URL = '/photos/ayush/manifest.json';

let cache: WallPhoto[] | null = null;
let inflight: Promise<WallPhoto[]> | null = null;

export const fetchWallPhotos = async (): Promise<WallPhoto[]> => {
  if (cache) return cache;
  if (!inflight) {
    inflight = fetch(MANIFEST_URL)
      .then((res) => (res.ok ? res.json() : []))
      .then((raw: unknown) => {
        const photos = Array.isArray(raw)
          ? (raw as WallPhoto[]).filter((photo) => typeof photo?.src === 'string')
          : [];
        if (photos.length > 0) cache = photos;
        else inflight = null;
        return photos;
      })
      .catch(() => {
        inflight = null;
        return [];
      });
  }
  return inflight;
};

/** Loads the manifest once and shares it across every photo-wall component. */
export const useWallPhotos = () => {
  const [photos, setPhotos] = useState<WallPhoto[]>(cache ?? []);
  const [loading, setLoading] = useState(cache === null);

  useEffect(() => {
    let active = true;
    fetchWallPhotos().then((list) => {
      if (!active) return;
      setPhotos(list);
      setLoading(false);
    });
    return () => {
      active = false;
    };
  }, []);

  return { photos, loading };
};

/** Warm the browser cache so the next/previous slide never shows a blank frame. */
export const preloadPhoto = (photo: WallPhoto | undefined) => {
  if (!photo || typeof window === 'undefined') return;
  const img = new Image();
  img.src = photo.src;
};

/**
 * Random visit order. `keepIndex` (the photo on screen) is spliced back in at
 * `keepAt`, so shuffling never yanks the picture the user is looking at.
 */
export const createShuffledOrder = (length: number, keepIndex?: number, keepAt = 0): number[] => {
  const rest = Array.from({ length }, (_, i) => i).filter((i) => i !== keepIndex);
  for (let i = rest.length - 1; i > 0; i -= 1) {
    const j = Math.floor(Math.random() * (i + 1));
    [rest[i], rest[j]] = [rest[j], rest[i]];
  }
  if (keepIndex === undefined) return rest;
  rest.splice(Math.min(Math.max(keepAt, 0), rest.length), 0, keepIndex);
  return rest;
};
